### ISSUE TITLE
Input/Output terminology confusing

### ISSUE THREAD

**Issue by Rotaerk** [Gabriel439/Haskell-Pipes-Concurrency-Library#43]
This library's choice of jargon is that a mailbox's message receiver is "output", and its message supplier is "input".  This makes sense from the perspective of a person interacting with a mailbox, since the message is going out of the person's hand (into the mailbox), or into the person's hand (from the mailbox).  However, if you flip the perspective to the mailbox itself, the reverse terminology makes sense.  Neither approach seems inherently superior to the other, but some people may intuit the wrong meanings of the terms, leading to confusion.

This arbitrariness suggests that these aren't quite the right words to use.  The phrases "output from the mailbox" and "input from the mailbox" essentially mean the same thing, just from different perspectives.  Similarly, "input to the mailbox" and "output to the mailbox" equivalently describe the flow of data.  The key words that distinguish them are the "to" and "from" and their direct objects, not the "input" and "output".

**Comment by Gabriel439** [comment]
I'm probably not going to change the name of these at this point, given the age of the library

I'm also not sure what a better naming scheme would be

**Comment by tonyday567** [comment]
Since we're just bike-shedding...

I think `input` and `output` are the right names for this particular job, and I find them intuitive to use.  Usually, I think of the computational event (that is usually anthropomorphized as a visually-challenged person) as central to the narrative drama and the messaging effect (aka the mailbox) as a piece of necessary but ultimately boring plumbing.  

So the in- and the out- seem natural directions.  `in` being a reserved word we need some sort of suffix, and -put comes from the latin 'putare' meaning 'to think', so an `input` is an effect going in to a think, and an `output` is an effect going out of a think.  Perfectly named.

**Comment by Rotaerk** [comment]
@Gabriel439 Regarding what a better naming scheme would be, perhaps Source instead of Input, and Sink instead of Output.  To me this seems less ambiguous, less dependent on whether you're thinking from the perspective of the user of the mailbox or from the perspective of the mailbox itself.  Of course, I understand your point about age.  It's probably too late to make such a change, now.  Should I just close this issue?

**Comment by Gabriel439** [comment]
Yeah, I'm probably not going to change the name, so I'll go ahead and close the issue
